name: Simulated Jenkins

# on:
#   push:
#     branches:
#       - master

# jobs:
#   jenkins-simulation:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Run Jenkinsfile Runner
#         uses: jenkinsci/jenkinsfile-runner-github-actions@v1

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  jenkins-pipeline:
    runs-on: ubuntu-latest 
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master  

    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v3

    
      - name: Run Jenkinsfile
        uses: jenkinsci/jfr-container-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile 
